### ISSUE TITLE
-bash: chromium-browser: command not found

### ISSUE THREAD

**Issue by HypePickups** [theriley106/outCaptcha#1]
Everytime I run the code 

chromium-browser --disable-web-security -user-data-dir=~/ & python3 app.py

I get this in the terminal

-bash: chromium-browser: command not found
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN:

(Idk if I should share my debugger pin so I left it out

**Comment by HypePickups** [comment]
Ok I just now dragged the folder into the extensions and I now have the extension how do I get my   Google Cloud Speech-To-Text API key??

**Comment by HypePickups** [comment]
I added the chrome extension into my pre existing browser and added in my api key. When I run the script then go to a url with a captcha on it nothing happens

**Comment by theriley106** [comment]
You didn't enable CORS in your browser.  You'll have to find out how to enable it in your version of Chrome.  It can't interact with the Captcha iframe without it, and the first line of the output says it couldn't open Chromium with CORS enabled (it looks like chromium isn't installed on your system).
