### ISSUE TITLE
sync-request.json not found

### ISSUE THREAD

**Issue by LeoSZN** [theriley106/outCaptcha#2]
Hi,

I counter an error and I need some assist.

1. I have drag the folder extension into normal chrome browser
2. download ffmpeg.exe
3. download chromedriver.exe
4. run app.py
5. access https://www.google.com/recaptcha/api2/demo
6.  The log message

 ``py app.py
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 848-271-019
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ImmutableMultiDict([('url', 'https://www.google.com/recaptcha/api2/payload?c=03AEMEkElJPHOOJSXajtPuoHncYceuPI_RRvMNmnOfVfGesjYcCNTbkfFVwuflKelNKPYd7cpXgJt6lFOSIPhpXRb_1j2smwe5ZnqIM9rj46klcmxzPFnUXtTjhXQDpxo81z9hUkOWjQp4RYueHJo6Dt6gLeOEdiF3d2i38-dTITUm6zCNbdlO1YhRhTIpH5QJWQNrTPf7fjFGEt1kK8-xjYLjjor01FLCBtNAg8NkaeQb7FCghynz63fnM9fIxLoibshmFtb6EYs3FY72uQ4BgPyvQGv8RMQJpBp-lAd8TL1KCcTjRalvkz0WFfcOMbu9inembH7FQjW8TYw7h4uOc7uWUgO2HIQWkZpGNQk8g65DRiILs-dOzZQAiEUYyL-g2zGx9secvP998ghjaq-piSvzjADCTVM8Zd8gni9DPtqBsII64snbwZzSu0pJ3AQSTGa3fj7MujPe-8p8h-TqMTuy7KiqnMLkVtlyM5q_YjO-bolx_lAPxwEf3oREdCJ_W6T9cZlDNQSW6jpLJO1ROPjEAsqC7exQNJd29DcXq0m66LynYymEmLzwtvsHFqhT2lIfWFSGUaBmoTwvpDjuj2KGiUFxG3Bd54PXE2B1ISchE5sER4RCYLsfbIiYHpFIGR3eYcZrbHebsksWW6Swhryy6oe0MuzXFiDLOAu-6Sb82IZVvWi3j5xHhlsoAw3th8zMZgIyguApwTMyqlPNlI7xU6t8vTpYttUOQmrMRji6YOIO_LiJmhmOSn4TZWHjcsSeCeTs34HNsEBC4Fhr4e5qEMrc7KcJXBuTdXOMuo7l2kkuIfgfc5hTREKZK162RGdMRJ9PWLeWCiDVgp6J67KFfW7M_BnFUhEIGjkAik8FMb5sSCwAw60Rrhne-fOH059-Sl31rXiILO2U0aAN_PPEsyT6lEEO9fVThEqPjYMdz88PmyRm4UsImPsLo6307z5jbiHXN9jrDeUEyPgD1Hl8M8ogKNO1mG7IcZ2tL6y-Lv8Muud_a41i7hndnrCDL4BhK9R0WOoA2rSsfPaOC24oTN4lIcNgNJFrSIlAM8u7ok8bXJ7USkYhwWubASom-QhPfKIDFIfAtRHazwbwATHZE7_GfBD-yE8Yb_mvbLlSj9vYZ5J8nRcXWP0tzUszcBQGpBRkmFg4INNCytJtGIgKeKFRh5HnaviWtGXQXCoc89Kk-2pctSDmfPH_9dFunGQqaVQCaliJ44uXmIVybydnoUFjhLlcFSyowAAgPOCWvfA7qVkTesnJvhc2fXCuco7V3eJDK1mt43ueFR5OCGzu4OhTv3A4vVHK8wKiQfkjHHiY3Lpc-BGN2fj-DqDPbG8x0Wq9mela0xVeSeqzUU0cz0rc_Z0kvU7lsFdANJdBDI45VX8hVMFGRwSJcLbqu51j8PLBoEKdFrkpRoQ1QV57HZDIML6Ev_oebJk02N4AkqZVHr1krRQk7ielMtu0YzV0VY63p4EOMHl94VSG67sWdGpAHsJYV3djAZIwTco5S_mOW1QJ4if2jrC3soEOw904qeR-ZtqJCV5zbH6v-FvY9vKhilENMLzrxGViKnZgtbeefnBMFPxd4x4NLAmogcc-w6k3Y2syZJx2n6jug-zuy5OPo9mOtMMA-xpTfth87oh6GeNEwI68YZdokhqDFY4nRnV-sY8Fg2_d5FTIECubc6648FTYk0NtEOXcnPxqQnx_bNDguAi3u8aEmktagxn9JEnO_Z4_&k=6Le-wvkSAAAAAPBMRTvw0Q4Muexq9bi0DJwx_mJ-'), ('apiKey', '6Le-wvkSAAAAAPBMRTvw0Q4Muexq9bi0DJwx_mJ-')])
6Le-wvkSAAAAAPBMRTvw0Q4Muexq9bi0DJwx_mJ-
ffmpeg version N-91520-gbce4da85e8 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7.3.1 (GCC) 20180722
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 18.102 / 56. 18.102
  libavcodec     58. 21.106 / 58. 21.106
  libavformat    58. 17.101 / 58. 17.101
  libavdevice    58.  4.101 / 58.  4.101
  libavfilter     7. 26.100 /  7. 26.100
  libswscale      5.  2.100 /  5.  2.100
  libswresample   3.  2.100 /  3.  2.100
  libpostproc    55.  2.100 / 55.  2.100
Input #0, mp3, from 'newAudio.mp3':
  Metadata:
    encoder         : Google
  Duration: 00:00:04.65, start: 0.050113, bitrate: 64 kb/s
    Stream #0:0: Audio: mp3, 22050 Hz, stereo, fltp, 64 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mp3 (mp3float) -> flac (native))
Press [q] to stop, [?] for help
[flac @ 000001906a2169c0] encoding as 24 bits-per-sample
Output #0, flac, to 'output.flac':
  Metadata:
    encoder         : Lavf58.17.101
    Stream #0:0: Audio: flac, 22050 Hz, mono, s32 (24 bit), 128 kb/s
    Metadata:
      encoder         : Lavc58.21.106 flac
size=     222kB time=00:00:04.57 bitrate= 396.9kbits/s speed= 353x
video:0kB audio:214kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 3.786567%
127.0.0.1 - - [27/Jul/2018 10:33:25] "POST / HTTP/1.1" 200 -``

When I run this command manually, it showing sync-request.json is empty
curl -X POST -H "Content-Type: application/json; charset=utf-8" --data @sync-request.json "https://speech.googleapis.com/v1/speech:recognize?key=6Le-wvkSAAAAAPBMRTvw0Q4Muexq9bi0DJwx_mJ-" -o result.json

Please advice.

**Comment by LeoSZN** [comment]
Is this project can run in windows?  Because I have hit error in  encode_audio() and curl -X POST -H "Content-Type: application/json; charset=utf-8" --data @sync-request.json "https://speech.googleapis.com/v1/speech:recognize?key={}" -o result.json

it showing invalid API key, but I have enter the API key (sitekey) manually

**Comment by nikkifr** [comment]
Same error. Did you solve it somehow?

**Comment by ORTIZSAM** [comment]
mismo error quien pudo porfa

**Comment by rafex** [comment]
ya no es posible usar este outCaptcha, la versión actualizada de ReCaptcha es la 3 e inmediatamente detecta esta función.
