### ISSUE TITLE
problem with Solves reCAPTCHA 2.0 Without Human Interaction

### ISSUE THREAD

**Issue by aminox77** [theriley106/outCaptcha#8]
hey when i try to run app.py it showing me this error : 
File "app.py", line 9
    print request.form
                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(request.form)?

**Comment by sghosh1810** [comment]
You are running on python 3 probably!

**Comment by ORTIZSAM** [comment]
hola podria decirme el scripts actualizados a la fecha 2019, ya estos no funcionan por favor
